### PR TITLE
Calculate the build script looking at submission status.

### PR DESCRIPTION
**Pull request by yanniboi**

### CODE REVIEW

**Comment by yanniboi** [comment]
I think we can probably include a fix to https://github.com/yanniboi/simplytest/issues/9 in this pull request.

**Comment by yanniboi** [comment]
I have combined the status and view routes to look as follows:

submissionview

**Comment by patrickd-** [comment]
Showing the used build-script in the submission info's is something i had thought about too. The only drawback generating it based on the submission data instead of storing the script that was actually used for each submission is that you cannot fully rely on the script being the exact same to what was sent to spawn.sh for that particular submission at the time.
On the other hand this would lead to tons of duplicate data in the long run.

Then there's the problem that the submission logs on spawn.sh are only available while the submission is still active, which too is bad for debugging the submission at a later point in time – but i'm probably going to change that and retain the logs for a longer time on spawn.sh, so that's probably nothing to worry about here.

**Review by patrickd- — APPROVED** [review]
This is good to go! Thanks! :+1:

**Pull request merged**
