### PR TITLE
Made README file markdown so it looks pretty and stuff

### PR DESCRIPTION
**Pull request by M1ke**
I made your readme file look nicer :-)

### CODE REVIEW

**Comment by yanniboi** [comment]
@M1ke++

Hero! Looks good to me. https://github.com/M1ke/simplytest/tree/patch-1

While we are here, might be nice to add one of them test passing images into the readme header?
(https://docs.travis-ci.com/user/status-images/)

**Comment by patrickd-** [comment]
Good idea! Thanks for joining us m1ke! ;)

```
 At the moment only simplytest_submission module exists for spawning
  submissions. After installing you'll need to set the spawn.sh access
  token with
```

I think this needs to be updated as we now have an actual installation profile. To make contributing as easy as possible this should updated (and kept up to date by future changes) to be a step-by-step setup guide.

**Comment by patrickd-** [comment]
We should also remove the linebreaks in markdown I think?

**Comment by yanniboi** [comment]
Ok, so something like this?

1. Ask Patrick nicely for a token (@patrickd_de on twitter).
2. Install simplytest install profile.
3. Set token using drush `drush sset simplytest_submission.service_token "TOKEN"`
4. Boom! Start contributing...

**Comment by patrickd-** [comment]
hmm.. maybe taking in account that the person reading it doesn't know much about simplytest.me..
1. Token? What for? (or is this enough covered by the architecture explanation?)
2. Install? What to download? Where to put it? (or can we assume this is obvious?)

But yeah, something like that!

**Comment by yanniboi** [comment]
Ok, so I think this needs some more thinking... Anyway @M1ke has a good commit here so lets not hold it up.

I've created a new branch out of 8.x-3.x -> feature/improve-readme

Lets merge this commit and then keep making improvements there before we merge into 8.x-3.x.

**Comment by yanniboi** [comment]
Thanks @M1ke :)

**Pull request merged**
