### PR TITLE
Improve the readme file with instructions of how to contribute

### PR DESCRIPTION
**Pull request by yanniboi**
We've started this here: https://github.com/yanniboi/simplytest/pull/28

We need better instructions about gettings started for someone who may not know much about simplytest.me

### CODE REVIEW

**Comment by yanniboi** [comment]
How to contribute.:

1. **Ask Patrick nicely for a token (@patrickd_de on twitter).**
    Spawn.sh is (currently) a closed service. You need an API token so that when you make requests, it allows your requests to pass. Patrick is in charge of spawn.sh and will manage who has tokens.
2. **Install simplytest install profile.**
    Simplytest for Drupal 8 is an install profile. Which means that when you install it, it will set up a log of configuration for you so that you don't have to. Simply download it from drupal.org and place the profile directory in [drupal_root]/profiles. The when installing (either via drush or through the web ui) choose simplytest as your installation profile.
3. **Set API token.** 
    The best way to do this is using Drush: 
    `drush drush sset simplytest_submission.service_token "TOKEN"`

    If you haven't got drush, you can also place the token in your settings.php file:

```
$settings['simplytest_submission'] = [
  'service_token' => 'TOKEN',
];
```

4. **Boom! Start contributing...**

**Comment by patrickd-** [comment]
> The when installing (either via drush or through the web ui) choose simplytest as your installation profile.

I don't think I ever had to choose it. Wasn't there some way to make sure your profile gets "exclusive" install right? Are we doing that?

Sounds good though!

**Comment by yanniboi** [comment]
Emm I don't think we are atm. I can check but that sounds like a good idea :p

**Review by patrickd- — APPROVED** [review]
Looks good :+1: thanks!

**Pull request merged**
